# Generated by Django 5.0.6 on 2024-07-10 19:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_car_value_carreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carreview',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
