# Generated by Django 5.0.6 on 2024-07-18 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_carphoto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarPhoto',
        ),
    ]
